-- 1. Create a separate warehouse to process data operations.
CREATE WAREHOUSE IF NOT EXISTS ARCADE_WH
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 300  -- Automatically suspend after 5 minutes of inactivity (300 seconds)
  AUTO_RESUME = TRUE  -- Automatically resume when a query is executed
  INITIALLY_SUSPENDED = TRUE;  -- Start in a suspended state

-- 2. Create a database to store data.
CREATE DATABASE IF NOT EXISTS ARCADE_DB;

-- 3. Create the medallion schemas in ARCADE_DB.
USE DATABASE ARCADE_DB;
CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;

-- 4. Create roles for data engineering and Airflow access.
CREATE ROLE IF NOT EXISTS DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS AIRFLOW;

-- 5. Grant warehouse usage to roles.
GRANT USAGE ON WAREHOUSE ARCADE_WH TO ROLE DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE ARCADE_WH TO ROLE AIRFLOW;

-- 6. Grant database usage to roles.
GRANT USAGE ON DATABASE ARCADE_DB TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE ARCADE_DB TO ROLE AIRFLOW;

-- 7. Grant ownership of schemas to the DATA_ENGINEER role.
GRANT OWNERSHIP ON SCHEMA ARCADE_DB.BRONZE TO ROLE DATA_ENGINEER;
GRANT OWNERSHIP ON SCHEMA ARCADE_DB.SILVER TO ROLE DATA_ENGINEER;
GRANT OWNERSHIP ON SCHEMA ARCADE_DB.GOLD   TO ROLE DATA_ENGINEER;

-- 8. Assign roles to the user.
GRANT ROLE DATA_ENGINEER TO USER YOUR_USER_NAME;
GRANT ROLE AIRFLOW TO USER YOUR_USER_NAME;

-- 9. Grant access to the AIRFLOW role.
GRANT USAGE ON SCHEMA ARCADE_DB.BRONZE TO ROLE AIRFLOW;
GRANT USAGE ON SCHEMA ARCADE_DB.SILVER TO ROLE AIRFLOW;
GRANT USAGE ON SCHEMA ARCADE_DB.GOLD   TO ROLE AIRFLOW;

-- 10. Grant future privileges to AIRFLOW for new objects in schemas.
GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA ARCADE_DB.BRONZE TO ROLE AIRFLOW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
    ON FUTURE TABLES IN SCHEMA ARCADE_DB.BRONZE TO ROLE AIRFLOW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
    ON FUTURE TABLES IN SCHEMA ARCADE_DB.SILVER TO ROLE AIRFLOW;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
    ON FUTURE TABLES IN SCHEMA ARCADE_DB.GOLD TO ROLE AIRFLOW;